version: "3.9"

services:
    mysql:
        image: mysql:8
        container_name: prestashop-db
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
        ports:
            - 3306:3306
        networks:
            - prestashop
        volumes:
            - prestashopdb:/var/lib/mysql 

    prestashop:
        build:
            context: .
            dockerfile: dockerfile
            args:
                USER_ID: "${USER_ID}"
                GROUP_ID: "${GROUP_ID}"
        container_name: prestashop
        environment:
            DB_SERVER: mysql
        ports:
            - 8080:80
        networks:
            - prestashop
        volumes:
            - ./:/var/www/html

networks:
    prestashop:
volumes:
    prestashopdb:
